services:

  nginx:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.nginx
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - application
      - application2
      - application3
    networks:
      - server-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M 
        reservations:
          cpus: '0.25'
          memory: 256M


networks:
  server-net:

volumes:
  shared-data: